### ISSUE TITLE
Clarity - What are index maps?

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-lib-geo/creating-index-maps#11]
At: https://ubc-lib-geo.github.io/creating-index-maps/content/what-are-index-maps.html

I think I understand what it means, but i had to re-read this phrase about 4 times to get it's meaning: "As map collections move online, the importance of index maps is even more apparent as disparate images of maps, often inadequately linked to adjacent sheets or the collection as a whole, are further removed from their counterparts in a digital space."

Maybe: "As map collections move online, disparate images of maps are often inadequately linked to adjacent sheets or the collection as a whole and are further removed from their counterparts in a digital space. So, the importance of index maps is even more apparent online."

**Comment by ElizabethFernandes** [comment]
@ect123 how long is this workshop designed to be?

**Comment by ect123** [comment]
Yes, that is a mouthful. 

How about: 

As map collections move online, the importance of index maps is even more apparent. In physical form, indexes are very often attached to, bound with, or in close proximity to the maps themselves. Online, disparate images of maps, often inadequately linked to adjacent sheets or the collection as a whole, are further removed from their index counterparts in a digital space.

**Comment by ect123** [comment]
This is not exactly meant to be a workshop, but rather a conglomeration of directions that can be used for tasks in a wider effort to create digital map indexes. Meant for a librarian audience.

**Comment by ElizabethFernandes** [comment]
Ok, I was just wondering because it is a long one and that it would make sense to take it slowly. And it focuses on librarians, now it all makes sense :D
