### ISSUE TITLE
create-virtual-layer-qgis.md

### ISSUE THREAD

**Issue by brettdimond** [ubc-lib-geo/creating-index-maps#5]
Under the **Add the spreadsheet inventory** section, under **Geometry Definition** > **Geometry CRS**, I changed the selection from **invalid projection** to **Project CRS: EPSG: 4326 - WGS 84**. Should this be included as an additional step?

**Comment by ect123** [comment]
When you added the spreadsheet as a csv, I don't think you need to assign it a CRS since it's just text. I'm going to close this for now, but if I'm misunderstanding, then feel free to reopen.
